# TryCatch

Try: funciona para efetuar um c贸digo que pode dar ero

catch: faz a mensagem do erro sem fechar o c贸digo

'''
try
{
	int v1 = 10;
	int v2 = 0;
	int calc = v1/v2;
	MessageBox.Show(calc);

}catch (Exception ex)
{
	MessageBox.Show("Erro: " + ex.message);
}
'''

dependendo do caso podendo usar o finally depois do catch para finalizar o c贸digo

'''
finally
{
        MessageBox.Show("C贸digo Finalizado");
	Close();
}
'''